import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-center items-center min-h-screen space-y-8">
        <h1 className="text-3xl">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div className="w-48">
          <Image src={require("../assets/images/vercel.svg")} alt="Vercel" />
        </div>
      </main>
    </div>
  );
}
