import Head from 'next/head';

const Home = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className="flex flex-col justify-center items-center min-h-screen">
      <img
        src={require('../assets/images/next.png')}
        alt="Next"
        className="w-48 mb-8"
      />
      <p className="text-huge">text-huge</p>
      <p className="text-large-1">text-large-1</p>
      <p className="text-large-2">text-large-2</p>
      <p className="text-headline-1">text-headline-1</p>
      <p className="text-headline-2">text-headline-2</p>
      <p>text-body-1 (default)</p>
      <p className="text-body-2">text-body-2</p>
      <p className="text-small-1">text-small-1</p>
      <p className="text-small-2">text-small-2</p>
    </main>
  </div>
);

export default Home;
